apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  # base64 encoded values
  # echo -n "1234" | base64 = MTIzNA==
  SPRING_DATASOURCE_PASSWORD: MTIzNA==
  MYSQL_ROOT_PASSWORD: MTIzNA==
  # JWT_SECRET is already base64 encoded
  JWT_SECRET: ZG1WeWVXeHZibWNnYzJWamNtVjBJR3RsZVNCbWIzSWdiRzlqWVd3Z1pHVjJaV3h2Y0cxbGJuUWdkWE5sSUc5dWJIa2dNVEl6TkRVMk56ZzVNQT09
