apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-db
spec:
  serviceName: "todo-db-svc"
  replicas: 1
  selector:
    matchLabels:
      app: todo-db
  template:
    metadata:
      labels:
        app: todo-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: todo-list-secret
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: todo-list-config
                  key: MYSQL_DATABASE
          volumeMounts:
            - name: todo-db-data
              mountPath: /var/lib/mysql
              subPath: mysql
  volumeClaimTemplates:
    - metadata:
        name: todo-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "local-path"  # ← 변경
        resources:
          requests:
            storage: 1Gi