# backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: todo-backend-service
spec:
  type: NodePort
  selector:
    app: todo-backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
