# frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  # ❗️ Service 타입을 명시하지 않으면 기본값인 ClusterIP로 생성됩니다.
  type: NodePort
  selector:
    app: todo-frontend
  ports:
    - protocol: TCP
      port: 3000 # Service가 노출할 포트
      targetPort: 3000 # Service가 연결할 Pod의 포트
      nodePort: 31000  # 외부에서 접속 가능