apiVersion: v1
kind: Service
metadata:
  name: todo-db-service
  labels:
    {{- include "todo-list-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  clusterIP: None
  ports:
  - port: 3306
    name: mysql
  selector:
    {{- include "todo-list-chart.database.selectorLabels" . | nindent 4 }}