apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-list-chart.fullname" . }}-db-secret
  labels:
    {{- include "todo-list-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
stringData:
  MYSQL_USER: {{ .Values.database.user | quote }}
  MYSQL_PASSWORD: {{ .Values.database.password | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.database.rootPassword | quote }}